Date26/12/2025

Airline Data Analytics Case-study | SQLite + Python¶

This project aims to address the challenges faced by a leading air transportation company through data analytics. The company is experiencing issues like stricter environmental regulations, higher flight taxes, increased labor costs, and rising fuel prices, which impact profitability and growth prospects. To ensure long-term sustainability and success, the company plans to analyze its database to increase aircraft occupancy rates and maximize average profit per seat.

Problem Statement

The airline company aims to enhance aircraft occupancy rates and identify strategic opportunities to increase profitability per seat. The key challenges are as follows:

Stricter environmental regulations: These regulations raise operating costs and restrict expansion potential.

Higher flight taxes: Increased taxes raise the overall cost of flying, reducing demand.

Tight labor market resulting in increased labor costs: Scarcity of skilled workers leads to higher labor costs and increased turnover rates.

In [4]:
import pandas as pd
import sqlite3     ## build in data set for sqlite file importation
import matplotlib.pyplot as plt
import warnings
warnings. filterwarnings('ignore')

In [5]:
con=sqlite3.connect("travel.sqlite")
cursor=con.cursor()   ## cursor is used to proform

In [6]:
query="""
       select name from sqlite_master where type ='table'
"""

In [10]:
table=pd.read_sql_query(query,con)

In [12]:
table

              name
0   aircrafts_data
1    airports_data
2  boarding_passes
3         bookings
4          flights
5            seats
6   ticket_flights
7          tickets

In [14]:
query = "SELECT * FROM aircrafts_data"
aircrafts_data = pd.read_sql_query(query, con)

In [16]:
aircrafts_data

  aircraft_code                                              model  range
0           773    {"en": "Boeing 777-300", "ru": "Боинг 777-300"}  11100
1           763    {"en": "Boeing 767-300", "ru": "Боинг 767-300"}   7900
2           SU9  {"en": "Sukhoi Superjet-100", "ru": "Сухой Суп...   3000
3           320  {"en": "Airbus A320-200", "ru": "Аэробус A320-...   5700
4           321  {"en": "Airbus A321-200", "ru": "Аэробус A321-...   5600
5           319  {"en": "Airbus A319-100", "ru": "Аэробус A319-...   6700
6           733    {"en": "Boeing 737-300", "ru": "Боинг 737-300"}   4200
7           CN1  {"en": "Cessna 208 Caravan", "ru": "Сессна 208...   1200
8           CR2  {"en": "Bombardier CRJ-200", "ru": "Бомбардье ...   2700

In [18]:
query = "SELECT * FROM airports_data"
airports_data = pd.read_sql_query(query, con)

In [20]:
airports_data

,airport_code,airport_name,city,coordinates,timezone
0,YKS,"{""en"": ""Yakutsk Airport"", ""ru"": ""Якутск""}","{""en"": ""Yakutsk"", ""ru"": ""Якутск""}","(129.77099609375,62.0932998657226562)",Asia/Yakutsk
1,MJZ,"{""en"": ""Mirny Airport"", ""ru"": ""Мирный""}","{""en"": ""Mirnyj"", ""ru"": ""Мирный""}","(114.03900146484375,62.534698486328125)",Asia/Yakutsk
2,KHV,"{""en"": ""Khabarovsk-Novy Airport"", ""ru"": ""Хабар...","{""en"": ""Khabarovsk"", ""ru"": ""Хабаровск""}","(135.18800354004,48.5279998779300001)",Asia/Vladivostok
3,PKC,"{""en"": ""Yelizovo Airport"", ""ru"": ""Елизово""}","{""en"": ""Petropavlovsk"", ""ru"": ""Петропавловск-К...","(158.453994750976562,53.1679000854492188)",Asia/Kamchatka
4,UUS,"{""en"": ""Yuzhno-Sakhalinsk Airport"", ""ru"": ""Хом...","{""en"": ""Yuzhno-Sakhalinsk"", ""ru"": ""Южно-Сахали...","(142.718002319335938,46.8886985778808594)",Asia/Sakhalin
...,...,...,...,...,...
99,MMK,"{""en"": ""Murmansk Airport"", ""ru"": ""Мурманск""}","{""en"": ""Murmansk"", ""ru"": ""Мурманск""}","(32.7508010864257812,68.7817001342773438)",Europe/Moscow
100,ABA,"{""en"": ""Abakan Airport"", ""ru"": ""Абакан""}","{""en"": ""Abakan"", ""ru"": ""Абакан""}","(91.3850021362304688,53.7400016784667969)",Asia/Krasnoyarsk
101,BAX,"{""en"": ""Barnaul Airport"", ""ru"": ""Барнаул""}","{""en"": ""Barnaul"", ""ru"": ""Барнаул""}","(83.5384979248046875,53.363800048828125)",Asia/Krasnoyarsk
102,AAQ,"{""en"": ""Anapa Vityazevo Airport"", ""ru"": ""Витяз...","{""en"": ""Anapa"", ""ru"": ""Анапа""}","(37.3473014831539984,45.002101898192997)",Europe/Moscow
103,CNN,"{""en"": ""Chulman Airport"", ""ru"": ""Чульман""}","{""en"": ""Neryungri"", ""ru"": ""Нерюнгри""}","(124.914001464839998,56.9138984680179973)",Asia/Yakutsk

In [22]:
query = "SELECT * FROM boarding_passes"
boarding_passes = pd.read_sql_query(query, con)

In [23]:
boarding_passes

            ticket_no  flight_id  boarding_no seat_no
0       0005435212351      30625            1      2D
1       0005435212386      30625            2      3G
2       0005435212381      30625            3      4H
3       0005432211370      30625            4      5D
4       0005435212357      30625            5     11A
...               ...        ...          ...     ...
579681  0005434302871      19945           85     20F
579682  0005432892791      19945           86     21C
579683  0005434302869      19945           87     20E
579684  0005432802476      19945           88     21F
579685  0005432802482      19945           89     21E

[579686 rows x 4 columns]

In [24]:
query = "SELECT * FROM bookings"
bookings = pd.read_sql_query(query, con)

In [27]:
bookings

       book_ref               book_date  total_amount
0        00000F  2017-07-05 03:12:00+03        265700
1        000012  2017-07-14 09:02:00+03         37900
2        000068  2017-08-15 14:27:00+03         18100
3        000181  2017-08-10 13:28:00+03        131800
4        0002D8  2017-08-07 21:40:00+03         23600
...         ...                     ...           ...
262783   FFFEF3  2017-07-17 07:23:00+03         56000
262784   FFFF2C  2017-08-08 05:55:00+03         10800
262785   FFFF43  2017-07-20 20:42:00+03         78500
262786   FFFFA8  2017-08-08 04:45:00+03         28800
262787   FFFFF7  2017-07-01 22:12:00+03         73600

[262788 rows x 3 columns]

In [30]:
query = "SELECT * FROM flights"
flights = pd.read_sql_query(query, con)

In [32]:
flights

,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival
0,1185,PG0134,2017-09-10 09:50:00+03,2017-09-10 14:55:00+03,DME,BTK,Scheduled,319,\N,\N
1,3979,PG0052,2017-08-25 14:50:00+03,2017-08-25 17:35:00+03,VKO,HMA,Scheduled,CR2,\N,\N
2,4739,PG0561,2017-09-05 12:30:00+03,2017-09-05 14:15:00+03,VKO,AER,Scheduled,763,\N,\N
3,5502,PG0529,2017-09-12 09:50:00+03,2017-09-12 11:20:00+03,SVO,UFA,Scheduled,763,\N,\N
4,6938,PG0461,2017-09-04 12:25:00+03,2017-09-04 13:20:00+03,SVO,ULV,Scheduled,SU9,\N,\N
...,...,...,...,...,...,...,...,...,...,...
33116,33117,PG0063,2017-08-02 19:25:00+03,2017-08-02 20:10:00+03,SKX,SVO,Arrived,CR2,2017-08-02 19:25:00+03,2017-08-02 20:10:00+03
33117,33118,PG0063,2017-07-28 19:25:00+03,2017-07-28 20:10:00+03,SKX,SVO,Arrived,CR2,2017-07-28 19:30:00+03,2017-07-28 20:15:00+03
33118,33119,PG0063,2017-09-08 19:25:00+03,2017-09-08 20:10:00+03,SKX,SVO,Scheduled,CR2,\N,\N
33119,33120,PG0063,2017-08-01 19:25:00+03,2017-08-01 20:10:00+03,SKX,SVO,Arrived,CR2,2017-08-01 19:26:00+03,2017-08-01 20:12:00+03
33120,33121,PG0063,2017-08-26 19:25:00+03,2017-08-26 20:10:00+03,SKX,SVO,Scheduled,CR2,\N,\N

In [34]:
query = "SELECT * FROM seats"
seats = pd.read_sql_query(query, con)

In [36]:
seats

     aircraft_code seat_no fare_conditions
0              319      2A        Business
1              319      2C        Business
2              319      2D        Business
3              319      2F        Business
4              319      3A        Business
...            ...     ...             ...
1334           773     48H         Economy
1335           773     48K         Economy
1336           773     49A         Economy
1337           773     49C         Economy
1338           773     49D         Economy

[1339 rows x 3 columns]

In [38]:
query = "SELECT * FROM ticket_flights"
ticket_flights = pd.read_sql_query(query, con)

In [39]:
ticket_flights

             ticket_no  flight_id fare_conditions  amount
0        0005432159776      30625        Business   42100
1        0005435212351      30625        Business   42100
2        0005435212386      30625        Business   42100
3        0005435212381      30625        Business   42100
4        0005432211370      30625        Business   42100
...                ...        ...             ...     ...
1045721  0005435097522      32094         Economy    5200
1045722  0005435097521      32094         Economy    5200
1045723  0005435104384      32094         Economy    5200
1045724  0005435104352      32094         Economy    5200
1045725  0005435104389      32094         Economy    5200

[1045726 rows x 4 columns]

In [40]:
query = "SELECT * FROM tickets"
tickets = pd.read_sql_query(query, con)

In [41]:
tickets

            ticket_no book_ref passenger_id
0       0005432000987   06B046  8149 604011
1       0005432000988   06B046  8499 420203
2       0005432000989   E170C3  1011 752484
3       0005432000990   E170C3  4849 400049
4       0005432000991   F313DD  6615 976589
...               ...      ...          ...
366728  0005435999869   D730BA  0474 690760
366729  0005435999870   D730BA  6535 751108
366730  0005435999871   A1AD46  1596 156448
366731  0005435999872   7B6A53  9374 822707
366732  0005435999873   7B6A53  7380 075822

[366733 rows x 3 columns]

In [42]:
cursor.execute("""select name from sqlite_master where type='table'""")
table_list =[table[0] for table in cursor.fetchall()]

In [45]:
table_list

['aircrafts_data',
 'airports_data',
 'boarding_passes',
 'bookings',
 'flights',
 'seats',
 'ticket_flights',
 'tickets']

In [49]:
query="""select name from sqlite_master where type='table'"""
tables=pd.read_sql_query(query,con)

In [52]:
tables

              name
0   aircrafts_data
1    airports_data
2  boarding_passes
3         bookings
4          flights
5            seats
6   ticket_flights
7          tickets

In [54]:
for t in table.name:
    print('\n Table :',t)
    print()
    columns_info=con.execute(f"PRAGMA table_info({t})")
    for column in columns_info.fetchall():
        print(column[0:3])

 Table : aircrafts_data

(0, 'aircraft_code', 'character(3)')
(1, 'model', 'jsonb')
(2, 'range', 'INTEGER')

 Table : airports_data

(0, 'airport_code', 'character(3)')
(1, 'airport_name', 'jsonb')
(2, 'city', 'jsonb')
(3, 'coordinates', 'point')
(4, 'timezone', 'TEXT')

 Table : boarding_passes

(0, 'ticket_no', 'character(13)')
(1, 'flight_id', 'INTEGER')
(2, 'boarding_no', 'INTEGER')
(3, 'seat_no', 'character varying(4)')

 Table : bookings

(0, 'book_ref', 'character(6)')
(1, 'book_date', 'timestamp with time zone')
(2, 'total_amount', 'numeric(10,2)')

 Table : flights

(0, 'flight_id', 'INTEGER')
(1, 'flight_no', 'character(6)')
(2, 'scheduled_departure', 'timestamp with time zone')
(3, 'scheduled_arrival', 'timestamp with time zone')
(4, 'departure_airport', 'character(3)')
(5, 'arrival_airport', 'character(3)')
(6, 'status', 'character varying(20)')
(7, 'aircraft_code', 'character(3)')
(8, 'actual_departure', 'timestamp with time zone')
(9, 'actual_arrival', 'timestamp with time zone')

 Table : seats

(0, 'aircraft_code', 'character(3)')
(1, 'seat_no', 'character varying(4)')
(2, 'fare_conditions', 'character varying(10)')

 Table : ticket_flights

(0, 'ticket_no', 'character(13)')
(1, 'flight_id', 'INTEGER')
(2, 'fare_conditions', 'character varying(10)')
(3, 'amount', 'numeric(10,2)')

 Table : tickets

(0, 'ticket_no', 'character(13)')
(1, 'book_ref', 'character(6)')
(2, 'passenger_id', 'character varying(20)')

In [56]:
tables_list = [
    aircrafts_data,
    airports_data,
    boarding_passes,
    bookings,
    flights,
    seats,
    ticket_flights,
    tickets
]

In [58]:
for t in tables_list:
    t.info()
    print()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   aircraft_code  9 non-null      object
 1   model          9 non-null      object
 2   range          9 non-null      int64
dtypes: int64(1), object(2)
memory usage: 344.0+ bytes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   airport_code  104 non-null    object
 1   airport_name  104 non-null    object
 2   city          104 non-null    object
 3   coordinates   104 non-null    object
 4   timezone      104 non-null    object
dtypes: object(5)
memory usage: 4.2+ KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 579686 entries, 0 to 579685
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   ticket_no    579686 non-null  object
 1   flight_id    579686 non-null  int64
 2   boarding_no  579686 non-null  int64
 3   seat_no      579686 non-null  object
dtypes: int64(2), object(2)
memory usage: 17.7+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262788 entries, 0 to 262787
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   book_ref      262788 non-null  object
 1   book_date     262788 non-null  object
 2   total_amount  262788 non-null  int64
dtypes: int64(1), object(2)
memory usage: 6.0+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33121 entries, 0 to 33120
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   flight_id            33121 non-null  int64
 1   flight_no            33121 non-null  object
 2   scheduled_departure  33121 non-null  object
 3   scheduled_arrival    33121 non-null  object
 4   departure_airport    33121 non-null  object
 5   arrival_airport      33121 non-null  object
 6   status               33121 non-null  object
 7   aircraft_code        33121 non-null  object
 8   actual_departure     33121 non-null  object
 9   actual_arrival       33121 non-null  object
dtypes: int64(1), object(9)
memory usage: 2.5+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   aircraft_code    1339 non-null   object
 1   seat_no          1339 non-null   object
 2   fare_conditions  1339 non-null   object
dtypes: object(3)
memory usage: 31.5+ KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1045726 entries, 0 to 1045725
Data columns (total 4 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   ticket_no        1045726 non-null  object
 1   flight_id        1045726 non-null  int64
 2   fare_conditions  1045726 non-null  object
 3   amount           1045726 non-null  int64
dtypes: int64(2), object(2)
memory usage: 31.9+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366733 entries, 0 to 366732
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ticket_no     366733 non-null  object
 1   book_ref      366733 non-null  object
 2   passenger_id  366733 non-null  object
dtypes: object(3)
memory usage: 8.4+ MB

In [60]:
for t in tables_list:
    print(t.isnull().sum())
    print()

aircraft_code    0
model            0
range            0
dtype: int64

airport_code    0
airport_name    0
city            0
coordinates     0
timezone        0
dtype: int64

ticket_no      0
flight_id      0
boarding_no    0
seat_no        0
dtype: int64

book_ref        0
book_date       0
total_amount    0
dtype: int64

flight_id              0
flight_no              0
scheduled_departure    0
scheduled_arrival      0
departure_airport      0
arrival_airport        0
status                 0
aircraft_code          0
actual_departure       0
actual_arrival         0
dtype: int64

aircraft_code      0
seat_no            0
fare_conditions    0
dtype: int64

ticket_no          0
flight_id          0
fare_conditions    0
amount             0
dtype: int64

ticket_no       0
book_ref        0
passenger_id    0
dtype: int64

In [62]:
#Question -1
#How many planes have more than 100 seats?


#query=("select * from seats")     ## SQL method
query = """
SELECT aircraft_code,
       COUNT(*) AS no_seats
FROM Seats
GROUP BY aircraft_code
HAVING COUNT(*) > 100
"""
Seats = pd.read_sql_query(query, con)
Seats

  aircraft_code  no_seats
0           319       116
1           320       140
2           321       170
3           733       130
4           763       222
5           773       402

In [64]:
query = "SELECT * FROM seats"
seats = pd.read_sql_query(query, con)
seats

     aircraft_code seat_no fare_conditions
0              319      2A        Business
1              319      2C        Business
2              319      2D        Business
3              319      2F        Business
4              319      3A        Business
...            ...     ...             ...
1334           773     48H         Economy
1335           773     48K         Economy
1336           773     49A         Economy
1337           773     49C         Economy
1338           773     49D         Economy

[1339 rows x 3 columns]

In [66]:
## 2 method
x = seats.groupby('aircraft_code')['aircraft_code'].count()
x[x>100]

aircraft_code
319    116
320    140
321    170
733    130
763    222
773    402
Name: aircraft_code, dtype: int64

In [68]:
query=("select Aircraft_code,count(*)as no_Seats group by Aircraft_code Having no_seats>100")

Seats=pd.read_sql_query(query,con)
#Seats

DatabaseError: Execution failed on sql 'select Aircraft_code,count(*)as no_Seats group by Aircraft_code Having no_seats>100': no such column: Aircraft_code

#Question-2
#How do the number of tickets booked and the total amount earned change with time?

In [70]:
query=("select * from tickets t inner join bookings b on t.book_ref=b.book_ref ")

Tickets=pd.read_sql_query(query,con)
Tickets

,ticket_no,book_ref,passenger_id,book_ref,book_date,total_amount
0,0005432000987,06B046,8149 604011,06B046,2017-07-05 20:19:00+03,12400
1,0005432000988,06B046,8499 420203,06B046,2017-07-05 20:19:00+03,12400
2,0005432000989,E170C3,1011 752484,E170C3,2017-06-29 01:55:00+03,24700
3,0005432000990,E170C3,4849 400049,E170C3,2017-06-29 01:55:00+03,24700
4,0005432000991,F313DD,6615 976589,F313DD,2017-07-03 04:37:00+03,30900
...,...,...,...,...,...,...
366728,0005435999869,D730BA,0474 690760,D730BA,2017-08-14 11:50:00+03,210600
366729,0005435999870,D730BA,6535 751108,D730BA,2017-08-14 11:50:00+03,210600
366730,0005435999871,A1AD46,1596 156448,A1AD46,2017-08-13 03:49:00+03,45900
366731,0005435999872,7B6A53,9374 822707,7B6A53,2017-08-15 15:54:00+03,219400
366732,0005435999873,7B6A53,7380 075822,7B6A53,2017-08-15 15:54:00+03,219400

In [77]:
query=("select * from tickets t inner join bookings b on t.book_ref=b.book_ref ")

Tickets=pd.read_sql_query(query,con)
Tickets

,ticket_no,book_ref,passenger_id,book_ref,book_date,total_amount
0,0005432000987,06B046,8149 604011,06B046,2017-07-05 20:19:00+03,12400
1,0005432000988,06B046,8499 420203,06B046,2017-07-05 20:19:00+03,12400
2,0005432000989,E170C3,1011 752484,E170C3,2017-06-29 01:55:00+03,24700
3,0005432000990,E170C3,4849 400049,E170C3,2017-06-29 01:55:00+03,24700
4,0005432000991,F313DD,6615 976589,F313DD,2017-07-03 04:37:00+03,30900
...,...,...,...,...,...,...
366728,0005435999869,D730BA,0474 690760,D730BA,2017-08-14 11:50:00+03,210600
366729,0005435999870,D730BA,6535 751108,D730BA,2017-08-14 11:50:00+03,210600
366730,0005435999871,A1AD46,1596 156448,A1AD46,2017-08-13 03:49:00+03,45900
366731,0005435999872,7B6A53,9374 822707,7B6A53,2017-08-15 15:54:00+03,219400
366732,0005435999873,7B6A53,7380 075822,7B6A53,2017-08-15 15:54:00+03,219400

In [79]:
query='''select passenger_id,book_date,b.book_ref,ticket_no,total_amount from 
bookings b inner join tickets t on b.book_ref = t.book_ref'''
tickets_booking=pd.read_sql_query(query,con)
tickets_booking

,passenger_id,book_date,book_ref,ticket_no,total_amount
0,1708 262537,2017-07-05 03:12:00+03,00000F,0005435838975,265700
1,9091 269355,2017-07-14 09:02:00+03,000012,0005432527326,37900
2,5895 674437,2017-08-15 14:27:00+03,000068,0005432293273,18100
3,6799 285573,2017-08-10 13:28:00+03,000181,0005435545944,131800
4,0929 739492,2017-08-10 13:28:00+03,000181,0005435545945,131800
...,...,...,...,...,...
366728,0169 339108,2017-07-20 20:42:00+03,FFFF43,0005433986163,78500
366729,0961 118506,2017-07-20 20:42:00+03,FFFF43,0005433986164,78500
366730,0563 487643,2017-08-08 04:45:00+03,FFFFA8,0005435426293,28800
366731,3211 278709,2017-07-01 22:12:00+03,FFFFF7,0005434343796,73600
366732,7581 746167,2017-07-01 22:12:00+03,FFFFF7,0005434343797,73600

In [81]:
tickets_booking['book_date']=pd.to_datetime(tickets_booking['book_date'])

In [ ]:
tickets_booking['book_']